CREATE TABLE IF NOT EXISTS dw.programs (
    prog_id	NUMBER,
    event_id NUMBER,
    prog_name VARCHAR(256),
    prog_gender	VARCHAR(256),
    prog_max_age NUMBER,
    prog_min_age NUMBER,
    prog_notes VARCHAR,
    prog_date_utc DATE,
    prog_time_utc VARCHAR(256),
    prog_timezone_offset VARCHAR(256),
    prog_distance_category VARCHAR(256),
    prog_distances VARIANT,
    is_race	BOOLEAN,
    is_results BOOLEAN,
    is_live_timing_enabled BOOLEAN,
    is_team	BOOLEAN,
    load_ts	TIMESTAMP_NTZ,
    CONSTRAINT prog_pk PRIMARY KEY (prog_id)
)